### ISSUE TITLE
Change forms layout

### ISSUE THREAD

**Issue by imobachgs** [dgdavid/cockpit-wicked#11]
Change the forms layout to be more like the rest of Cockpit plugins (with the label at the left of the fields).

**Comment by dgdavid** [comment]
It's true, they use left-aligned labels, as can be seen when, for example, adding a bond, bridge or vlan in the Networking module.

![Screenshot from 2020-10-28 02-27-24](https://user-images.githubusercontent.com/1691872/97383270-226b1880-18c5-11eb-8c9e-b29cd4919502.png)

However, in [their own guidelines](https://www.patternfly.org/v4/components/form/design-guidelines#labels) they encourage for using the top-aligned labels approach.

> Left-aligned labels are another available form option. They are useful for layouts with more horizontal space than vertical. **However, as a general rule, they should be avoided in favor of top-aligned labels.**

**Comment by imobachgs** [comment]
Let's keep the top-aligned labels then. I am closing this issue by now. Thanks for checking it!
