### ISSUE TITLE
Read/write routing information

### ISSUE THREAD

**Issue by imobachgs** [dgdavid/cockpit-wicked#18]
Routes are being ignored by the `WickedAdapter` at this point. We need to make them work by:

* Getting routing information from Wicked (and `/etc/sysconfig/network/routes` file if needed).
* Writing routes to `/etc/sysconfig/network/ifcfg-*` files.

**Comment by dgdavid** [comment]
Just for the record, this issue was initially addressed in https://github.com/dgdavid/cockpit-wicked/pull/41, where we concluded that another iteration is needed for rethinking and improving how to manage/deal with routes.

So, let's close this issue in favor of a more specific one.
