### ISSUE TITLE
IP configuration improvements

### ISSUE THREAD

**Issue by imobachgs** [dgdavid/cockpit-wicked#27]
We have merged the support to specify IP settings (see #22). However, we might introduce a few improvements:

- [x] Filter out 'DHCPv6'  and 'DHCPv4' from the protocol selector.
- [x] Improve how the configuration is displayed in the interface summary. For instance, replace `dhcp` by `DHCP` (or `Automatic (DHCP)`. If the configuration is `static`, show the configured IP address.
- [x] Selecting `static` in the `Boot Protocol` should force the user to introduce, at least, an IP address.

Additionally, now we need to write IP settings to the `ifcfg` files (see #19).

**Comment by dgdavid** [comment]
>     * [x]  Selecting `static` in the `Boot Protocol` should force the user to introduce, at least, an IP address.

Done in #31

**Comment by dgdavid** [comment]
>     * [x]  Improve how the configuration is displayed in the interface summary. For instance, replace `dhcp` by `DHCP` (or `Automatic (DHCP)`. If the configuration is `static`, show the configured IP address.
> 

Done in #29 (https://github.com/dgdavid/cockpit-wicked/pull/29/commits/b57e104088a65da861d00ac591ab26a499bf4c7a) and #31 (f904e9a0a2f4147f31f77c66f623bb8220f1ae80)

**Comment by dgdavid** [comment]
>     * [x]  Filter out 'DHCPv6'  and 'DHCPv4' from the protocol selector.

Done in #31 (https://github.com/dgdavid/cockpit-wicked/pull/31/commits/2755fc9a33301438b5d5518cecabfe4fafc497e1). For now, the selector displays only the boot protocols supported by wicked.
